// SPDX-License-Identifier: MIT
// Copyright 2026 Tom F. (https://github.com/tomtom215)

//! The `2026-07-28` half of the check inventory.
//!
//! Split from [`super`] when the combined list crossed the 500-line cap, at the
//! seam that will keep holding: one revision's rows per file, concatenated into
//! `ALL` at compile time.

use super::Check;
use crate::checks::stateless;

macro_rules! check {
    ($id:literal, $run:path) => {
        Check { id: $id, run: $run }
    };
}

/// The revision's rows, in stable order.
pub(super) const ROWS: &[Check] = &[
    check!(
        "base.result-type-present",
        stateless::envelope::result_type_present
    ),
    check!(
        "base.request-id-unique-in-flight",
        stateless::envelope::request_id_unique_in_flight
    ),
    check!(
        "base.error-code-legacy-subrange",
        stateless::envelope::error_code_legacy_subrange
    ),
    check!(
        "base.error-code-reserved-subrange",
        stateless::envelope::error_code_reserved_subrange
    ),
    check!(
        "base.error-code-withdrawn",
        stateless::envelope::error_code_withdrawn
    ),
    check!(
        "base.error-code-application-range",
        stateless::envelope::error_code_application_range
    ),
    check!(
        "meta.required-request-fields",
        stateless::meta::required_request_fields
    ),
    check!(
        "meta.missing-required-field-rejected",
        stateless::meta::missing_required_field_rejected
    ),
    check!(
        "meta.missing-required-field-http-status",
        stateless::meta::missing_required_field_http_status
    ),
    check!(
        "meta.missing-capability-error",
        stateless::meta::missing_capability_error
    ),
    check!(
        "meta.missing-capability-http-status",
        stateless::meta::missing_capability_http_status
    ),
    check!(
        "meta.no-undeclared-capability-reliance",
        stateless::meta::no_undeclared_capability_reliance
    ),
    check!(
        "meta.subscription-id-present",
        stateless::meta::subscription_id_present
    ),
    check!(
        "meta.trace-context-format",
        stateless::meta::trace_context_format
    ),
    check!(
        "transport.protocol-version-header-present",
        stateless::transport::protocol_version_header_present
    ),
    check!(
        "transport.protocol-version-header-matches-body",
        stateless::transport::protocol_version_header_matches_body
    ),
    check!(
        "transport.request-metadata-headers",
        stateless::transport::request_metadata_headers
    ),
    check!(
        "transport.client-no-responses",
        stateless::transport::client_no_responses
    ),
    check!(
        "transport.no-independent-server-requests",
        stateless::transport::no_independent_server_requests
    ),
    check!(
        "transport.accel-buffering-header",
        stateless::transport::accel_buffering_header
    ),
    check!(
        "transport.no-messages-after-cancellation",
        stateless::transport::no_messages_after_cancellation
    ),
    check!(
        "transport.version-mismatch-rejected",
        stateless::transport::version_mismatch_rejected
    ),
    check!(
        "transport.invalid-param-header-rejected",
        stateless::transport::invalid_param_header_rejected
    ),
    check!(
        "transport.header-mismatch-status",
        stateless::transport::header_mismatch_status
    ),
    check!(
        "transport.header-body-match-validated",
        stateless::transport::header_body_match_validated
    ),
    check!(
        "transport.unsupported-version-error",
        stateless::transport::unsupported_version_error
    ),
    check!(
        "transport.unsupported-version-status",
        stateless::transport::unsupported_version_status
    ),
    check!(
        "transport.unknown-method-404",
        stateless::transport::unknown_method_404
    ),
    check!(
        "transport.header-value-encoding",
        stateless::transport::header_value_encoding
    ),
    check!(
        "transport.sentinel-marker-case",
        stateless::transport::sentinel_marker_case
    ),
    check!(
        "transport.sentinel-pattern-encoded",
        stateless::transport::sentinel_pattern_encoded
    ),
    check!(
        "transport.x-mcp-header-mirrored",
        stateless::transport::x_mcp_header_mirrored
    ),
    check!(
        "transport.x-mcp-header-name-valid",
        stateless::transport::x_mcp_header_name_valid
    ),
    check!("discover.implemented", stateless::discovery::implemented),
    check!(
        "discover.dual-era-probe-first",
        stateless::discovery::dual_era_probe_first
    ),
    check!(
        "versioning.retry-uses-supported-version",
        stateless::versioning::retry_uses_supported_version
    ),
    check!(
        "versioning.extension-identifier-format",
        stateless::versioning::extension_identifier_format
    ),
    check!(
        "versioning.initialize-error-names-versions",
        stateless::versioning::initialize_error_names_versions
    ),
    check!(
        "transport.cancel-notification-references-request",
        stateless::transport::cancel_notification_references_request
    ),
    check!(
        "transport.no-messages-after-cancel-notification",
        stateless::transport::no_messages_after_cancel_notification
    ),
    check!(
        "mrtr.input-required-supported-methods",
        stateless::mrtr::input_required_supported_methods
    ),
    check!(
        "mrtr.input-request-methods",
        stateless::mrtr::input_request_methods
    ),
    check!(
        "mrtr.input-required-has-content",
        stateless::mrtr::input_required_has_content
    ),
    check!(
        "mrtr.retry-carries-input-responses",
        stateless::mrtr::retry_carries_input_responses
    ),
    check!(
        "mrtr.request-state-echoed",
        stateless::mrtr::request_state_echoed
    ),
    check!(
        "mrtr.no-unsolicited-request-state",
        stateless::mrtr::no_unsolicited_request_state
    ),
    check!("mrtr.retry-id-differs", stateless::mrtr::retry_id_differs),
    check!(
        "mrtr.request-state-scoped-to-retry",
        stateless::mrtr::request_state_scoped_to_retry
    ),
    check!(
        "mrtr.missing-input-reasked",
        stateless::mrtr::missing_input_reasked
    ),
    check!(
        "subscriptions.only-requested-notifications",
        stateless::subscriptions::only_requested_notifications
    ),
    check!(
        "subscriptions.acknowledgment-first",
        stateless::subscriptions::acknowledgment_first
    ),
    check!(
        "subscriptions.graceful-close-result-shape",
        stateless::subscriptions::graceful_close_result_shape
    ),
    check!(
        "caching.hints-on-cacheable-results",
        stateless::caching::hints_on_cacheable_results
    ),
    check!(
        "caching.ttl-non-negative",
        stateless::caching::ttl_non_negative
    ),
    check!(
        "caching.page-scope-consistent",
        stateless::caching::page_scope_consistent
    ),
    check!(
        "capabilities.completions-declared",
        stateless::capabilities::completions_declared
    ),
    check!(
        "capabilities.logging-declared",
        stateless::capabilities::logging_declared
    ),
    check!(
        "logging.level-requested",
        stateless::logging::level_requested
    ),
    check!(
        "logging.not-on-subscription",
        stateless::logging::not_on_subscription
    ),
    check!(
        "logging.invalid-level-rejected",
        stateless::logging::invalid_level_rejected
    ),
    check!(
        "capabilities.tools-declared",
        stateless::capabilities::tools_declared
    ),
    check!(
        "capabilities.resources-declared",
        stateless::capabilities::resources_declared
    ),
    check!(
        "capabilities.prompts-declared",
        stateless::capabilities::prompts_declared
    ),
    check!(
        "capabilities.tools-list-implemented",
        stateless::capabilities::tools_list_implemented
    ),
    check!(
        "capabilities.resources-list-implemented",
        stateless::capabilities::resources_list_implemented
    ),
    check!(
        "capabilities.prompts-list-implemented",
        stateless::capabilities::prompts_list_implemented
    ),
    check!(
        "capabilities.embedded-resource-declared",
        stateless::capabilities::embedded_resource_declared
    ),
    check!(
        "tools.deterministic-order",
        stateless::features::deterministic_order
    ),
    check!(
        "tools.x-mcp-header-integer-range",
        stateless::features::x_mcp_header_integer_range
    ),
    check!(
        "resources.read-contents-non-empty",
        stateless::features::read_contents_non_empty
    ),
];
