// SPDX-License-Identifier: MIT
// Copyright 2026 Tom F. (https://github.com/tomtom215)

//! The server type and its [`ServerHandler`] implementation.
//!
//! One rule governs `get_info`: **advertise only what is implemented.** A
//! conformance reference that claims a capability and then answers
//! `method not found` would fail the very suite it exists to pass, so the
//! capability set below grows commit-by-commit with the modules that
//! implement it — tools, resources (with subscriptions), prompts, logging,
//! and completions today.
//!
//! The same rule chooses the protocol revision. [`ServedRevision`] selects it
//! once, when the server is built: `2025-11-25` by default, `2026-07-28` when
//! asked. Everything the newer revision changes about what this handler
//! *answers* — the version it negotiates, the version list it advertises, the
//! SEP-2549 caching hints on cacheable results — reads that one value, so the
//! default surface has no new branch to take and is unchanged byte for byte.
//! What the newer revision changes about how requests are *routed* (no
//! sessions, per-request `_meta` required) is the transport's business and
//! lives in [`crate::http`].
//!
//! Two of the six cacheable operations are not reached from here.
//! `tools/list` and `prompts/list` are generated by rmcp's `#[tool_handler]`
//! and `#[prompt_handler]` macros, which emit their own hints (a zero TTL,
//! public scope) whenever the *request* negotiated `2026-07-28`; the prompt
//! macro overwrites a hand-written `list_prompts` outright, so aligning the
//! two on this crate's TTL is not available without forking the macro. Both
//! shapes are conformant — SEP-2549 requires the hint, not a particular
//! lifetime — and a corpus carrying both is the better capture.

// SEP-2577 forward-deprecates Roots, Sampling and Logging. They remain fully
// functional and REQUIRED on the `2025-11-25` surface this crate implements
// and the official suite exercises, so rmcp 3.x's deprecation attributes fire
// on correct code — here, Logging. Scoped to this module, never the crate:
// a blanket allow would also hide a deprecation that genuinely matters. The
// honest cost is that a *different* future deprecation in this module would
// be silenced too. Retires when the `2025-11-25` surface does.
#![allow(deprecated)]
use std::borrow::Cow;
use std::collections::HashSet;
use std::sync::{Arc, Mutex};

use rmcp::handler::server::router::prompt::PromptRouter;
use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::model::{
    CompleteRequestParams, CompleteResult, CompletionInfo, DiscoverResult, ErrorData as McpError,
    Implementation, InitializeRequestParams, InitializeResult, ListResourceTemplatesResult,
    ListResourcesResult, LoggingLevel, PaginatedRequestParams, ProtocolVersion,
    ReadResourceRequestParams, ReadResourceResponse, Reference, ResourceUpdatedNotificationParam,
    ServerCapabilities, ServerInfo, SetLevelRequestParams, SubscribeRequestParams,
    UnsubscribeRequestParams,
};
use rmcp::service::RequestContext;
use rmcp::{RoleServer, ServerHandler, prompt_handler, tool_handler};

use crate::{logging, resources};

mod caching;
mod revision;
pub mod stateless;
pub use revision::ServedRevision;

/// Upper bound on tracked subscriptions per session. Far above any legitimate
/// use (the suite exercises a handful) and low enough that an adversarial
/// client subscribing to endless distinct URIs cannot grow this server's
/// bookkeeping without bound.
const MAX_SUBSCRIPTIONS: usize = 1024;

/// Reference MCP server exercising the MCP protocol surface.
///
/// Construct with [`EverythingServer::new`] for `2025-11-25` or
/// [`EverythingServer::serving`] to choose a [`ServedRevision`], then serve
/// over any rmcp transport — stdio for subprocess wiring, streamable HTTP
/// behind the default-secure [`crate::policy::HttpSecurityPolicy`].
#[derive(Debug)]
pub struct EverythingServer {
    pub(crate) tool_router: ToolRouter<Self>,
    pub(crate) prompt_router: PromptRouter<Self>,
    /// URIs the client subscribed to (`resources/subscribe` bookkeeping).
    subscriptions: Arc<Mutex<HashSet<String>>>,
    /// Threshold set via `logging/setLevel`; messages below it are dropped.
    log_level: Arc<Mutex<LoggingLevel>>,
    /// The protocol revision this instance presents.
    revision: ServedRevision,
}

impl EverythingServer {
    /// Creates the server with every implemented capability wired, serving the
    /// default revision ([`ServedRevision::V2025_11_25`]).
    #[must_use]
    pub fn new() -> Self {
        Self::serving(ServedRevision::default())
    }

    /// Creates the server presenting `revision`.
    #[must_use]
    pub fn serving(revision: ServedRevision) -> Self {
        Self {
            tool_router: crate::tools::all_tools(),
            prompt_router: Self::prompt_router_all(),
            subscriptions: Arc::new(Mutex::new(HashSet::new())),
            log_level: Arc::new(Mutex::new(logging::default_level())),
            revision,
        }
    }

    /// The protocol revision this instance presents.
    #[must_use]
    pub const fn revision(&self) -> ServedRevision {
        self.revision
    }

    /// `result`, with SEP-2549 caching hints when the served revision defines
    /// them.
    fn cached<T: caching::Cacheable>(&self, result: T) -> T {
        caching::applied(self.revision, result)
    }

    /// Whether a message at `candidate` level passes the current threshold.
    pub(crate) fn log_permits(&self, candidate: LoggingLevel) -> bool {
        let threshold = self.log_level.lock().map_or_else(
            // A poisoned lock means a panicked writer; failing open keeps
            // diagnostics flowing exactly when something is going wrong.
            |poisoned| *poisoned.into_inner(),
            |level| *level,
        );
        logging::permits(threshold, candidate)
    }

    /// Snapshot of the subscribed URIs (test and tap support).
    #[must_use]
    pub fn subscribed_uris(&self) -> Vec<String> {
        let mut uris: Vec<String> = self.subscriptions.lock().map_or_else(
            |poisoned| poisoned.into_inner().iter().cloned().collect(),
            |subscriptions| subscriptions.iter().cloned().collect(),
        );
        uris.sort();
        uris
    }

    /// Records a subscription; returns whether the URI was newly tracked.
    ///
    /// The set is capped at [`MAX_SUBSCRIPTIONS`]: a client cannot grow this
    /// server's per-session bookkeeping without bound by subscribing to an
    /// endless stream of distinct URIs. At the cap, a new URI is refused (not
    /// tracked, no acknowledgement) while already-tracked URIs still re-confirm.
    pub(crate) fn track_subscription(&self, uri: String) -> bool {
        self.subscriptions.lock().is_ok_and(|mut subscriptions| {
            if subscriptions.contains(&uri) {
                return false;
            }
            if subscriptions.len() >= MAX_SUBSCRIPTIONS {
                return false;
            }
            subscriptions.insert(uri)
        })
    }

    /// Drops a subscription; returns whether the URI had been tracked.
    pub(crate) fn untrack_subscription(&self, uri: &str) -> bool {
        self.subscriptions
            .lock()
            .is_ok_and(|mut subscriptions| subscriptions.remove(uri))
    }
}

impl Default for EverythingServer {
    fn default() -> Self {
        Self::new()
    }
}

#[tool_handler(router = self.tool_router)]
#[prompt_handler(router = self.prompt_router)]
impl ServerHandler for EverythingServer {
    fn get_info(&self) -> ServerInfo {
        // Not `Implementation::from_build_env()`: that helper expands
        // `env!(..)` inside rmcp and therefore always says "rmcp 1.x".
        ServerInfo::new(
            ServerCapabilities::builder()
                .enable_tools()
                .enable_tool_list_changed()
                .enable_resources()
                .enable_resources_subscribe()
                .enable_resources_list_changed()
                .enable_prompts()
                .enable_prompts_list_changed()
                .enable_logging()
                .enable_completions()
                .build(),
        )
        .with_server_info(Implementation::new(
            env!("CARGO_PKG_NAME"),
            env!("CARGO_PKG_VERSION"),
        ))
        .with_protocol_version(self.revision.protocol_version())
        .with_instructions(self.revision.instructions().to_owned())
    }

    async fn initialize(
        &self,
        request: InitializeRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<InitializeResult, McpError> {
        let supported = self.supported_protocol_versions();
        if self.revision.is_stateless() {
            // A server serving only the stateless revision has no handshake to
            // complete, and rmcp's default would complete one anyway: its
            // negotiation answers an unsupported request with the server's own
            // version rather than an error. A legacy client would then read a
            // successful `initialize`, believe itself connected, and have every
            // subsequent request rejected for want of per-request metadata it
            // does not know to send.
            //
            // The refusal is `-32022` carrying `data.supported`, which is both
            // what VERS-001 requires of a version refusal and the diagnostic
            // VERS-008 asks a modern-only server to give a legacy client — the
            // one message such a client can surface, since it has no
            // fall-forward mechanism of its own.
            return Err(McpError::unsupported_protocol_version(
                request.protocol_version,
                &supported,
            ));
        }
        // rmcp's default body for the legacy surface, restated because
        // overriding a trait method forgoes it and its negotiation helper is
        // crate-private. Kept behaviourally identical on purpose: agree to the
        // requested version when it is one this server supports, and otherwise
        // answer with the server's own — the `2025-11-25` lifecycle rule,
        // which leaves the decision to disconnect with the client.
        context.peer.set_peer_info(request.clone());
        let mut info = self.get_info();
        if supported.contains(&request.protocol_version) {
            info.protocol_version = request.protocol_version;
        }
        Ok(info)
    }

    fn supported_protocol_versions(&self) -> Cow<'static, [ProtocolVersion]> {
        match self.revision {
            // rmcp's default: every revision the SDK knows. Kept verbatim so
            // the legacy surface negotiates exactly as it did before this
            // method existed — narrowing it is a change to what `initialize`
            // may agree to, and belongs to whoever needs it, not here.
            ServedRevision::V2025_11_25 => Cow::Borrowed(ProtocolVersion::KNOWN_VERSIONS),
            // The stateless surface advertises only itself. This is not
            // cosmetic: the transport requires per-request protocol metadata
            // in this mode, and a client negotiated below `2026-07-28` does
            // not send it — so a version this list admitted would be a version
            // whose ordinary requests the transport then rejects.
            ServedRevision::V2026_07_28 => Cow::Owned(vec![ProtocolVersion::V_2026_07_28]),
        }
    }

    async fn discover(
        &self,
        _context: RequestContext<RoleServer>,
    ) -> Result<DiscoverResult, McpError> {
        // rmcp's default body, plus the caching hints its conservative
        // constructor leaves at "immediately stale, private". This result is
        // the same constant for every caller, so saying so is the honest hint
        // — and `server/discover` is the one call a client makes before it can
        // make any other, which is precisely where a reusable answer earns its
        // keep.
        Ok(self.cached(DiscoverResult::from_server_info(
            self.supported_protocol_versions().into_owned(),
            self.get_info(),
        )))
    }

    async fn list_resources(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, McpError> {
        // rmcp 3.x added SEP-2322's `result_type` and SEP-2549's
        // `ttl_ms`/`cache_scope` to every list result. Build through rmcp's
        // constructor rather than a literal: it sets `result_type` to
        // `COMPLETE` and rmcp's server handler *clears* that field for peers
        // that negotiated a pre-`2026-07-28` revision, so the `2025-11-25`
        // wire shape is unchanged while the type stays correct for the newer
        // revision. Setting the fields by hand would defeat that clearing.
        Ok(self.cached(ListResourcesResult::with_all_items(resources::catalog())))
    }

    async fn list_resource_templates(
        &self,
        _request: Option<PaginatedRequestParams>,
        _context: RequestContext<RoleServer>,
    ) -> Result<ListResourceTemplatesResult, McpError> {
        Ok(self.cached(ListResourceTemplatesResult::with_all_items(
            resources::templates(),
        )))
    }

    async fn read_resource(
        &self,
        request: ReadResourceRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResponse, McpError> {
        // MRTR (SEP-2322) turned this return into a union of Complete /
        // InputRequired. Nothing this server serves needs a second round trip
        // — the bodies are constants — so the only correct variant is
        // Complete, at either revision, and `.into()` is the single seam that
        // guarantees it: `From<ReadResourceResult>` constructs `Complete` and
        // nothing else. See `call_tool` for the same seam on the tools side.
        resources::read(&request.uri)
            .map(|result| self.cached(result).into())
            .ok_or_else(|| {
                McpError::resource_not_found(
                    "resource not found",
                    Some(serde_json::json!({ "uri": request.uri })),
                )
            })
    }

    async fn subscribe(
        &self,
        request: SubscribeRequestParams,
        context: RequestContext<RoleServer>,
    ) -> Result<(), McpError> {
        // An immediate update notification acknowledges the subscription in
        // an observable way (the idiom rmcp's own notification example uses);
        // the spec leaves update timing to the server.
        if self.track_subscription(request.uri.clone()) {
            let _ = context
                .peer
                .notify_resource_updated(ResourceUpdatedNotificationParam::new(request.uri))
                .await;
        }
        Ok(())
    }

    async fn unsubscribe(
        &self,
        request: UnsubscribeRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<(), McpError> {
        self.untrack_subscription(&request.uri);
        Ok(())
    }

    async fn set_level(
        &self,
        request: SetLevelRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<(), McpError> {
        if let Ok(mut level) = self.log_level.lock() {
            *level = request.level;
        }
        Ok(())
    }

    async fn complete(
        &self,
        request: CompleteRequestParams,
        _context: RequestContext<RoleServer>,
    ) -> Result<CompleteResult, McpError> {
        // The completion-complete scenario's documented example: prefix
        // completion over arg1 of test_prompt_with_arguments. Anything else
        // completes to nothing — minimal support is explicitly conformant.
        const CANDIDATES: [&str; 3] = ["paris", "park", "party"];
        let values = match &request.r#ref {
            Reference::Prompt(prompt)
                if prompt.name == "test_prompt_with_arguments"
                    && request.argument.name == "arg1" =>
            {
                CANDIDATES
                    .iter()
                    .filter(|candidate| candidate.starts_with(&request.argument.value))
                    .map(ToString::to_string)
                    .collect()
            }
            // `Reference` became `#[non_exhaustive]` in rmcp 3.x. Completing
            // to nothing is the conformant answer for every reference this
            // server does not special-case, so the catch-all carries the same
            // meaning the explicit arms did — and a future variant inherits
            // it rather than breaking the build.
            _ => Vec::new(),
        };
        let completion = CompletionInfo::with_all_values(values).map_err(|message| {
            McpError::internal_error(
                "completion overflow",
                Some(serde_json::json!({ "message": message })),
            )
        })?;
        Ok(CompleteResult::new(completion))
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests;
