// SPDX-License-Identifier: MIT
// Copyright 2026 Tom F. (https://github.com/tomtom215)

//! The `coverage` task: generate the per-area requirement-coverage table the README
//! embeds between `coverage:begin` / `coverage:end` markers.
//!
//! ADR-0001 forbids hand-maintained counts in prose; this task makes the README's
//! numbers a *projection of the registry* instead. `cargo xtask coverage` rewrites the
//! block; `cargo xtask coverage --check` (run by CI and `cargo xtask ci`) fails when
//! the committed README has drifted from the registry.

// `unreachable_pub` (rustc) and `redundant_pub_crate` (clippy nursery) make
// opposite demands about items in a binary crate's private modules; this follows
// the rustc lint and quiets the clippy one, per its own known-problems note.
#![allow(clippy::redundant_pub_crate)]

use core::fmt::Write as _;
use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;
use std::process::ExitCode;

use mcp_conformance_core::requirement::{Registry, Requirement, Verification};

const BEGIN: &str =
    "<!-- coverage:begin (generated by `cargo xtask coverage`; do not edit by hand) -->";
const END: &str = "<!-- coverage:end -->";

/// Generates (or, with `check`, verifies) the README coverage block.
pub(crate) fn run(check: bool) -> ExitCode {
    let registry = match Registry::builtin_2025_11_25() {
        Ok(registry) => registry,
        Err(error) => {
            eprintln!("xtask: embedded registry failed to load: {error}");
            return ExitCode::FAILURE;
        }
    };
    let readme_path = readme_path();
    let readme = match fs::read_to_string(&readme_path) {
        Ok(text) => text,
        Err(error) => {
            eprintln!("xtask: cannot read {}: {error}", readme_path.display());
            return ExitCode::FAILURE;
        }
    };
    let Some(updated) = splice(&readme, &render(&registry)) else {
        eprintln!(
            "xtask: README.md lacks the `{BEGIN}` … `{END}` markers; cannot place the coverage table"
        );
        return ExitCode::FAILURE;
    };

    if check {
        if updated == readme {
            eprintln!("xtask: README coverage table is in sync with the registry");
            ExitCode::SUCCESS
        } else {
            eprintln!(
                "xtask: README coverage table is out of date — run `cargo xtask coverage` and commit the diff"
            );
            ExitCode::FAILURE
        }
    } else {
        match fs::write(&readme_path, updated) {
            Ok(()) => {
                eprintln!("xtask: README coverage table regenerated");
                ExitCode::SUCCESS
            }
            Err(error) => {
                eprintln!("xtask: cannot write {}: {error}", readme_path.display());
                ExitCode::FAILURE
            }
        }
    }
}

/// The workspace README, located relative to this crate so the task works from any
/// working directory inside the workspace.
fn readme_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../README.md")
}

/// Replaces the text between the markers (exclusive) with the rendered table.
fn splice(readme: &str, table: &str) -> Option<String> {
    let begin = readme.find(BEGIN)? + BEGIN.len();
    let end = readme[begin..].find(END)? + begin;
    let mut out = String::with_capacity(readme.len() + table.len());
    out.push_str(&readme[..begin]);
    out.push('\n');
    out.push_str(table);
    out.push_str(&readme[end..]);
    Some(out)
}

struct AreaRow {
    area: String,
    requirements: u32,
    checked: u32,
    excluded: u32,
    gated: u32,
}

fn render(registry: &Registry) -> String {
    let mut rows: Vec<AreaRow> = Vec::new();
    let mut distinct_checks: BTreeSet<&str> = BTreeSet::new();
    for requirement in registry.requirements() {
        let area = requirement.id.area();
        if rows.last().is_none_or(|row| row.area != area) {
            rows.push(AreaRow {
                area: area.to_owned(),
                requirements: 0,
                checked: 0,
                excluded: 0,
                gated: 0,
            });
        }
        if let Some(row) = rows.last_mut() {
            row.requirements += 1;
            tally(row, requirement, &mut distinct_checks);
        }
    }

    let mut out = String::new();
    out.push_str("| Area | Requirements | Checked | Excluded | Capability-gated |\n");
    out.push_str("|------|-------------:|--------:|---------:|-----------------:|\n");
    let mut totals = AreaRow {
        area: String::new(),
        requirements: 0,
        checked: 0,
        excluded: 0,
        gated: 0,
    };
    for row in &rows {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} | {} |",
            row.area, row.requirements, row.checked, row.excluded, row.gated
        );
        totals.requirements += row.requirements;
        totals.checked += row.checked;
        totals.excluded += row.excluded;
        totals.gated += row.gated;
    }
    let _ = writeln!(
        out,
        "| **Total** | **{}** | **{}** | **{}** | **{}** |",
        totals.requirements, totals.checked, totals.excluded, totals.gated
    );
    let _ = writeln!(
        out,
        "\nRevision `{}`: {} requirements — {} judged by {} distinct trace checks (every \
         check falsified by a committed violation trace), {} carrying documented \
         exclusions explaining why a recorded trace cannot judge them. Capability-gated \
         requirements report *not-applicable* (never a vacuous pass) for sessions that \
         did not negotiate the capability.",
        registry.revision(),
        totals.requirements,
        totals.checked,
        distinct_checks.len(),
        totals.excluded,
    );
    out
}

fn tally<'a>(row: &mut AreaRow, requirement: &'a Requirement, checks: &mut BTreeSet<&'a str>) {
    match &requirement.verification {
        Verification::Checks { checks: ids } => {
            row.checked += 1;
            for id in ids {
                checks.insert(id);
            }
        }
        Verification::Excluded { .. } => row.excluded += 1,
        // `Verification` is #[non_exhaustive]; counting a future arm as neither
        // checked nor excluded keeps the table conservative until handled.
        _ => {}
    }
    if requirement.capability.is_some() {
        row.gated += 1;
    }
}
