// SPDX-License-Identifier: MIT
// Copyright 2026 Tom F. (https://github.com/tomtom215)

//! `cargo xtask draft-coverage` — project the committed `2026-07-28` capture
//! reports into `corpus/README.md`, and verify the coverage claims the
//! user-facing Markdown makes in prose.
//!
//! ADR-0001 forbids hand-maintained counts in prose, and this is the second
//! place they accumulate. [`coverage`](crate::coverage) already makes the
//! per-area table a projection of the registry; what it cannot reach is *what
//! the captures evidence*, which is a property of the committed golden reports
//! rather than of the registry. Those numbers were kept by hand until this
//! task existed, and every one of them had drifted: a capture judged at 89 was
//! written up as 90, a union of five captures was attributed to three, a split
//! of 8-and-7 was written "Seven … Eight", and one crate README reported the
//! *judgeable total* as though every clause had passed. None of that is
//! catchable by review — it is catchable by arithmetic, which is what this is.
//!
//! Two mechanisms, because the counts appear in two shapes:
//!
//! - **The generated block.** `corpus/README.md` carries a table between
//!   `draft-coverage:begin` / `draft-coverage:end` markers: one row per
//!   capture, plus the union and the clauses no capture reaches. `--check`
//!   fails when the committed block has drifted from the reports.
//! - **The claim check.** Prose says things like "109 of the 124 judgeable
//!   clauses", and a table cannot stop a sentence elsewhere from disagreeing
//!   with it. Every occurrence of that phrasing in the user-facing Markdown is
//!   parsed and required to name a real pair: the denominator must be the
//!   judgeable total, and the numerator must be either the union or some
//!   single capture's judged count.
//!
//! The claim check reads a named set of current documents rather than every
//! tracked Markdown file — see `claims.rs`, which owns that half.

// `unreachable_pub` (rustc) and `redundant_pub_crate` (clippy nursery) make
// opposite demands about items in a binary crate's private modules; this
// follows the rustc lint and quiets the clippy one, per its known-problems note.
#![allow(clippy::redundant_pub_crate)]

use core::fmt::Write as _;
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use serde::Deserialize;

const BEGIN: &str = "<!-- draft-coverage:begin (generated by `cargo xtask draft-coverage`; do not edit by hand) -->";
const END: &str = "<!-- draft-coverage:end -->";

/// Generates (or, with `check`, verifies) the corpus coverage block and every
/// coverage claim in the shipped Markdown.
pub(crate) fn run(check: bool) -> ExitCode {
    let root = workspace_root();
    let (captures, summary) = match load(&root) {
        Ok(loaded) => loaded,
        Err(error) => {
            eprintln!("xtask: draft-coverage — {error}");
            return ExitCode::FAILURE;
        }
    };
    let readme_path = root.join("corpus/README.md");
    let readme = match fs::read_to_string(&readme_path) {
        Ok(text) => text,
        Err(error) => {
            eprintln!("xtask: cannot read {}: {error}", readme_path.display());
            return ExitCode::FAILURE;
        }
    };
    let Some(updated) = splice(&readme, &render(&captures, &summary)) else {
        eprintln!(
            "xtask: corpus/README.md lacks the `{BEGIN}` … `{END}` markers; cannot place the coverage table"
        );
        return ExitCode::FAILURE;
    };
    if !check {
        return match fs::write(&readme_path, updated) {
            Ok(()) => {
                eprintln!("xtask: corpus coverage table regenerated");
                ExitCode::SUCCESS
            }
            Err(error) => {
                eprintln!("xtask: cannot write {}: {error}", readme_path.display());
                ExitCode::FAILURE
            }
        };
    }
    exit_if(verify(&root, &readme, &updated, &captures, &summary))
}

/// Reads every capture and summarizes it, refusing a corpus it cannot
/// meaningfully union.
fn load(root: &Path) -> Result<(Vec<Capture>, Summary), String> {
    let captures = captures(root)?;
    if captures.is_empty() {
        return Err("no captures under corpus/draft/captured; nothing to project".to_owned());
    }
    let summary = Summary::of(&captures);
    // Every capture must have been judged against the same registry, or the
    // union is arithmetic over two different denominators — a way to report
    // more clauses than exist. It cannot happen while all the captures are one
    // revision's, which is exactly why it should be checked rather than
    // assumed.
    for capture in &captures {
        if capture.judgeable() != summary.judgeable {
            return Err(format!(
                "capture {} judges {} clauses but the corpus judges {}; \
                 the reports do not share a registry",
                capture.name,
                capture.judgeable(),
                summary.judgeable
            ));
        }
    }
    Ok((captures, summary))
}

/// The `--check` half: the committed block and every prose claim.
fn verify(
    root: &Path,
    readme: &str,
    updated: &str,
    captures: &[Capture],
    summary: &Summary,
) -> bool {
    let table_ok = updated == readme;
    if !table_ok {
        eprintln!(
            "xtask: corpus coverage table is out of date — run `cargo xtask draft-coverage` and commit the diff"
        );
    }
    // Bound before the `&&`, so a stale table never hides a wrong claim: an
    // operator fixing one wants to see both in the same run.
    let claims_ok = claims::check(root, summary);
    let ok = table_ok && claims_ok;
    if ok {
        eprintln!(
            "xtask: draft-coverage — {} captures evidence {} of {} judgeable clauses; every prose claim agrees",
            captures.len(),
            summary.observed,
            summary.judgeable
        );
    }
    ok
}

const fn exit_if(ok: bool) -> ExitCode {
    if ok {
        ExitCode::SUCCESS
    } else {
        ExitCode::FAILURE
    }
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..")
}

/// One committed golden report, read for its per-requirement outcomes only.
#[derive(Deserialize)]
struct GoldenReport {
    requirements: Vec<GoldenRow>,
}

#[derive(Deserialize)]
struct GoldenRow {
    id: String,
    outcome: String,
}

/// What one capture evidences.
pub(crate) struct Capture {
    name: String,
    pass: u32,
    fail: u32,
    warn: u32,
    observed: BTreeSet<String>,
    not_observed: BTreeSet<String>,
}

impl Capture {
    /// Clauses this capture judged, one way or the other.
    fn judged(&self) -> usize {
        self.observed.len()
    }

    fn judgeable(&self) -> usize {
        self.observed.len() + self.not_observed.len()
    }
}

/// Every capture, in the order `corpus/draft/captured` names them.
///
/// The capture list is derived from the recordings rather than hard-coded:
/// a new `.jsonl` with a golden report beside it joins the table by existing,
/// and one whose report is missing is an error rather than a silent omission.
fn captures(root: &Path) -> Result<Vec<Capture>, String> {
    let captured = root.join("corpus/draft/captured");
    let mut stems: Vec<String> = Vec::new();
    let entries = fs::read_dir(&captured)
        .map_err(|error| format!("cannot read {}: {error}", captured.display()))?;
    for entry in entries {
        let path = entry
            .map_err(|error| format!("cannot read {}: {error}", captured.display()))?
            .path();
        if path.extension().is_some_and(|ext| ext == "jsonl")
            && let Some(stem) = path.file_stem().and_then(|stem| stem.to_str())
        {
            stems.push(stem.to_owned());
        }
    }
    stems.sort();

    stems
        .into_iter()
        .map(|stem| {
            let report = root.join(format!("corpus/golden/draft/{stem}.json"));
            let text = fs::read_to_string(&report).map_err(|error| {
                format!(
                    "capture {stem} has no golden report at {}: {error}",
                    report.display()
                )
            })?;
            let parsed: GoldenReport = serde_json::from_str(&text)
                .map_err(|error| format!("{} is not a report: {error}", report.display()))?;
            Ok(tally(stem, &parsed))
        })
        .collect()
}

/// Sorts one report's rows into the buckets the table reports.
///
/// `excluded`, `unsupported` and `not-applicable` are all *un*judgeable and
/// deliberately fall through: a clause the registry excludes, or one whose
/// check was not compiled in, or one gated on a capability the session never
/// negotiated, is not something the capture could have evidenced.
fn tally(name: String, report: &GoldenReport) -> Capture {
    let mut capture = Capture {
        name,
        pass: 0,
        fail: 0,
        warn: 0,
        observed: BTreeSet::new(),
        not_observed: BTreeSet::new(),
    };
    for row in &report.requirements {
        match row.outcome.as_str() {
            "pass" => capture.pass += 1,
            "fail" => capture.fail += 1,
            "warn" => capture.warn += 1,
            "not-observed" => {
                capture.not_observed.insert(row.id.clone());
                continue;
            }
            _ => continue,
        }
        capture.observed.insert(row.id.clone());
    }
    capture
}

/// The union across every capture: what the corpus evidences as a whole.
pub(crate) struct Summary {
    observed: usize,
    judgeable: usize,
    /// Judged by no capture at all, in id order.
    never: Vec<String>,
    /// Every per-capture judged count, for the claim check's allowed set.
    per_capture: BTreeSet<usize>,
}

impl Summary {
    fn of(captures: &[Capture]) -> Self {
        let mut observed: BTreeSet<&String> = BTreeSet::new();
        let mut judgeable: BTreeSet<&String> = BTreeSet::new();
        let mut per_capture = BTreeSet::new();
        for capture in captures {
            observed.extend(capture.observed.iter());
            judgeable.extend(capture.observed.iter());
            judgeable.extend(capture.not_observed.iter());
            per_capture.insert(capture.judged());
        }
        let never = judgeable
            .iter()
            .filter(|id| !observed.contains(*id))
            .map(|id| (*id).clone())
            .collect();
        Self {
            observed: observed.len(),
            judgeable: judgeable.len(),
            never,
            per_capture,
        }
    }

    /// The numerators prose may legitimately use with [`Self::judgeable`].
    fn allowed(&self) -> BTreeSet<usize> {
        let mut allowed = self.per_capture.clone();
        allowed.insert(self.observed);
        allowed
    }
}

fn render(captures: &[Capture], summary: &Summary) -> String {
    let mut out = String::new();
    out.push_str("| Capture | Judged | pass | fail | warn | Not observed |\n");
    out.push_str("|---------|-------:|-----:|-----:|-----:|-------------:|\n");
    for capture in captures {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} | {} | {} | {} |",
            capture.name,
            capture.judged(),
            capture.pass,
            capture.fail,
            capture.warn,
            capture.not_observed.len(),
        );
    }
    let _ = writeln!(
        out,
        "| **Union** | **{}** | | | | **{}** |",
        summary.observed,
        summary.judgeable - summary.observed,
    );
    let _ = writeln!(
        out,
        "\nAcross all {} captures, **{} of the {} judgeable clauses** are evidenced by at \
         least one recording. Each capture's own judged count is what *that* recording \
         carried subject matter for; everything else it reports *not observed* rather \
         than counting it as a pass.",
        captures.len(),
        summary.observed,
        summary.judgeable,
    );
    if summary.never.is_empty() {
        let _ = writeln!(out, "\nNo clause goes unevidenced.");
    } else {
        let ids = summary
            .never
            .iter()
            .map(|id| format!("`{id}`"))
            .collect::<Vec<_>>()
            .join(", ");
        let plural = if summary.never.len() == 1 { "" } else { "s" };
        let _ = writeln!(
            out,
            "\nThe {} clause{plural} no capture reaches: {ids}.",
            summary.never.len(),
        );
    }
    out
}

/// Replaces the text between the markers (exclusive) with the rendered block.
fn splice(readme: &str, block: &str) -> Option<String> {
    let begin = readme.find(BEGIN)? + BEGIN.len();
    let end = readme[begin..].find(END)? + begin;
    let mut out = String::with_capacity(readme.len() + block.len());
    out.push_str(&readme[..begin]);
    out.push('\n');
    out.push_str(block);
    out.push_str(&readme[end..]);
    Some(out)
}

mod claims;

#[cfg(test)]
mod tests;
